// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: accounts.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, plan, settings, product_mode)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAccountParams struct {
	Name        string          `json:"name"`
	Plan        string          `json:"plan"`
	Settings    json.RawMessage `json:"settings"`
	ProductMode string          `json:"product_mode"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.Plan,
		arg.Settings,
		arg.ProductMode,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAccountByID = `-- name: DeleteAccountByID :execresult
DELETE FROM accounts
WHERE id = $1
`

func (q *Queries) DeleteAccountByID(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteAccountByID, id)
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, plan, product_mode, settings, created_at
FROM accounts
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Plan        string          `json:"plan"`
	ProductMode string          `json:"product_mode"`
	Settings    json.RawMessage `json:"settings"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.ProductMode,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountProductModeForUpdate = `-- name: GetAccountProductModeForUpdate :one
SELECT product_mode
FROM accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAccountProductModeForUpdate(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAccountProductModeForUpdate, id)
	var product_mode string
	err := row.Scan(&product_mode)
	return product_mode, err
}

const getAccountSettings = `-- name: GetAccountSettings :one
SELECT settings
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountSettings(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getAccountSettings, id)
	var settings json.RawMessage
	err := row.Scan(&settings)
	return settings, err
}

const getAccountSlug = `-- name: GetAccountSlug :one
SELECT slug
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountSlug(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getAccountSlug, id)
	var slug *string
	err := row.Scan(&slug)
	return slug, err
}

const mergeAccountSettings = `-- name: MergeAccountSettings :execresult
UPDATE accounts
SET settings = settings || $1::jsonb
WHERE id = $2
`

type MergeAccountSettingsParams struct {
	Settings json.RawMessage `json:"settings"`
	ID       uuid.UUID       `json:"id"`
}

func (q *Queries) MergeAccountSettings(ctx context.Context, arg MergeAccountSettingsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, mergeAccountSettings, arg.Settings, arg.ID)
}

const setAccountSlug = `-- name: SetAccountSlug :exec
UPDATE accounts
SET slug = $1
WHERE id = $2
`

type SetAccountSlugParams struct {
	Slug *string   `json:"slug"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) SetAccountSlug(ctx context.Context, arg SetAccountSlugParams) error {
	_, err := q.db.Exec(ctx, setAccountSlug, arg.Slug, arg.ID)
	return err
}

const updateAccountName = `-- name: UpdateAccountName :exec
UPDATE accounts
SET name = $1
WHERE id = $2
`

type UpdateAccountNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAccountName(ctx context.Context, arg UpdateAccountNameParams) error {
	_, err := q.db.Exec(ctx, updateAccountName, arg.Name, arg.ID)
	return err
}

const updateAccountProductMode = `-- name: UpdateAccountProductMode :exec
UPDATE accounts
SET product_mode = $1,
    settings = jsonb_set(COALESCE(settings, '{}'::jsonb), '{lead_tracking_enabled}', $2::jsonb)
WHERE id = $3
`

type UpdateAccountProductModeParams struct {
	ProductMode         string          `json:"product_mode"`
	LeadTrackingEnabled json.RawMessage `json:"lead_tracking_enabled"`
	ID                  uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateAccountProductMode(ctx context.Context, arg UpdateAccountProductModeParams) error {
	_, err := q.db.Exec(ctx, updateAccountProductMode, arg.ProductMode, arg.LeadTrackingEnabled, arg.ID)
	return err
}

const updateAccountSettings = `-- name: UpdateAccountSettings :exec
UPDATE accounts
SET settings = $1
WHERE id = $2
`

type UpdateAccountSettingsParams struct {
	Settings json.RawMessage `json:"settings"`
	ID       uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateAccountSettings(ctx context.Context, arg UpdateAccountSettingsParams) error {
	_, err := q.db.Exec(ctx, updateAccountSettings, arg.Settings, arg.ID)
	return err
}
