// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: conversations.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getConversationAccountAndAssignedUsers = `-- name: GetConversationAccountAndAssignedUsers :one
SELECT account_id, assigned_user_ids
FROM conversations
WHERE id = $1
`

type GetConversationAccountAndAssignedUsersRow struct {
	AccountID       uuid.UUID   `json:"account_id"`
	AssignedUserIds []uuid.UUID `json:"assigned_user_ids"`
}

func (q *Queries) GetConversationAccountAndAssignedUsers(ctx context.Context, id uuid.UUID) (GetConversationAccountAndAssignedUsersRow, error) {
	row := q.db.QueryRow(ctx, getConversationAccountAndAssignedUsers, id)
	var i GetConversationAccountAndAssignedUsersRow
	err := row.Scan(&i.AccountID, &i.AssignedUserIds)
	return i, err
}

const getConversationAssignedUsers = `-- name: GetConversationAssignedUsers :one
SELECT assigned_user_ids
FROM conversations
WHERE id = $1 AND account_id = $2
`

type GetConversationAssignedUsersParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) GetConversationAssignedUsers(ctx context.Context, arg GetConversationAssignedUsersParams) ([]uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getConversationAssignedUsers, arg.ID, arg.AccountID)
	var assigned_user_ids []uuid.UUID
	err := row.Scan(&assigned_user_ids)
	return assigned_user_ids, err
}

const unassignUserFromConversations = `-- name: UnassignUserFromConversations :exec
UPDATE conversations
SET assigned_user_ids = array_remove(assigned_user_ids, $1::uuid)
WHERE account_id = $2 AND $1::uuid = ANY(assigned_user_ids)
`

type UnassignUserFromConversationsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) UnassignUserFromConversations(ctx context.Context, arg UnassignUserFromConversationsParams) error {
	_, err := q.db.Exec(ctx, unassignUserFromConversations, arg.UserID, arg.AccountID)
	return err
}
