// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getMessageForNotification = `-- name: GetMessageForNotification :one
SELECT id, account_id, conversation_id, direction, sender_type, sender_user_id, content_type, content, external_message_id, created_at
FROM messages
WHERE id = $1 AND account_id = $2
`

type GetMessageForNotificationParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

type GetMessageForNotificationRow struct {
	ID                uuid.UUID       `json:"id"`
	AccountID         uuid.UUID       `json:"account_id"`
	ConversationID    uuid.UUID       `json:"conversation_id"`
	Direction         string          `json:"direction"`
	SenderType        string          `json:"sender_type"`
	SenderUserID      *uuid.UUID      `json:"sender_user_id"`
	ContentType       string          `json:"content_type"`
	Content           json.RawMessage `json:"content"`
	ExternalMessageID *string         `json:"external_message_id"`
	CreatedAt         time.Time       `json:"created_at"`
}

func (q *Queries) GetMessageForNotification(ctx context.Context, arg GetMessageForNotificationParams) (GetMessageForNotificationRow, error) {
	row := q.db.QueryRow(ctx, getMessageForNotification, arg.ID, arg.AccountID)
	var i GetMessageForNotificationRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ConversationID,
		&i.Direction,
		&i.SenderType,
		&i.SenderUserID,
		&i.ContentType,
		&i.Content,
		&i.ExternalMessageID,
		&i.CreatedAt,
	)
	return i, err
}
