// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Account struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Plan        string          `json:"plan"`
	Settings    json.RawMessage `json:"settings"`
	CreatedAt   time.Time       `json:"created_at"`
	ProductMode string          `json:"product_mode"`
	Slug        *string         `json:"slug"`
}

type AccountAiProvider struct {
	AccountID       uuid.UUID `json:"account_id"`
	BaseUrl         string    `json:"base_url"`
	EncryptedApiKey string    `json:"encrypted_api_key"`
	AnalysisModel   string    `json:"analysis_model"`
	ReplyModel      string    `json:"reply_model"`
	EmbeddingModel  string    `json:"embedding_model"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type AiAnswerEvent struct {
	ID             uuid.UUID      `json:"id"`
	AccountID      uuid.UUID      `json:"account_id"`
	ConversationID uuid.UUID      `json:"conversation_id"`
	MessageID      uuid.UUID      `json:"message_id"`
	StageMatched   string         `json:"stage_matched"`
	Confidence     pgtype.Numeric `json:"confidence"`
	Action         string         `json:"action"`
	ReplyMessageID *uuid.UUID     `json:"reply_message_id"`
	CreatedAt      time.Time      `json:"created_at"`
}

type AiReplyDraft struct {
	ID              uuid.UUID      `json:"id"`
	AccountID       uuid.UUID      `json:"account_id"`
	ConversationID  uuid.UUID      `json:"conversation_id"`
	SourceMessageID uuid.UUID      `json:"source_message_id"`
	DraftText       string         `json:"draft_text"`
	StageMatched    string         `json:"stage_matched"`
	Confidence      pgtype.Numeric `json:"confidence"`
	Status          string         `json:"status"`
	UsedMessageID   *uuid.UUID     `json:"used_message_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type AuditLog struct {
	ID          uuid.UUID       `json:"id"`
	AccountID   uuid.UUID       `json:"account_id"`
	ActorUserID *uuid.UUID      `json:"actor_user_id"`
	Action      string          `json:"action"`
	TargetType  string          `json:"target_type"`
	TargetID    *uuid.UUID      `json:"target_id"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
}

type AutomationSuggestion struct {
	ID               uuid.UUID          `json:"id"`
	AccountID        uuid.UUID          `json:"account_id"`
	Type             string             `json:"type"`
	SourceMessageIds []uuid.UUID        `json:"source_message_ids"`
	ProposedPayload  json.RawMessage    `json:"proposed_payload"`
	Confidence       pgtype.Numeric     `json:"confidence"`
	Status           string             `json:"status"`
	ReviewedBy       *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

type Channel struct {
	ID              uuid.UUID       `json:"id"`
	AccountID       uuid.UUID       `json:"account_id"`
	Type            string          `json:"type"`
	Status          string          `json:"status"`
	StatusDetail    *string         `json:"status_detail"`
	CreatedAt       time.Time       `json:"created_at"`
	Label           *string         `json:"label"`
	Provider        *string         `json:"provider"`
	RemoteAccountID *string         `json:"remote_account_id"`
	Capabilities    json.RawMessage `json:"capabilities"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type Contact struct {
	ID                  uuid.UUID  `json:"id"`
	AccountID           uuid.UUID  `json:"account_id"`
	ChannelID           uuid.UUID  `json:"channel_id"`
	ExternalIdentity    string     `json:"external_identity"`
	DisplayName         *string    `json:"display_name"`
	AvatarUrl           *string    `json:"avatar_url"`
	MergedIntoContactID *uuid.UUID `json:"merged_into_contact_id"`
	CreatedAt           time.Time  `json:"created_at"`
}

type Conversation struct {
	ID               uuid.UUID          `json:"id"`
	AccountID        uuid.UUID          `json:"account_id"`
	ContactID        uuid.UUID          `json:"contact_id"`
	ChannelID        uuid.UUID          `json:"channel_id"`
	Status           string             `json:"status"`
	AssignedUserIds  []uuid.UUID        `json:"assigned_user_ids"`
	LastMessageAt    pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt        time.Time          `json:"created_at"`
	ExternalThreadID *string            `json:"external_thread_id"`
}

type ConversationAiState struct {
	ConversationID            uuid.UUID          `json:"conversation_id"`
	AccountID                 uuid.UUID          `json:"account_id"`
	State                     string             `json:"state"`
	StateReason               *string            `json:"state_reason"`
	ReplyOverride             string             `json:"reply_override"`
	RunState                  string             `json:"run_state"`
	RunStartedAt              pgtype.Timestamptz `json:"run_started_at"`
	GenerationEpoch           int64              `json:"generation_epoch"`
	CooldownLevel             int16              `json:"cooldown_level"`
	NextReviewAt              pgtype.Timestamptz `json:"next_review_at"`
	UnansweredCount           int32              `json:"unanswered_count"`
	UnansweredWindowStartedAt pgtype.Timestamptz `json:"unanswered_window_started_at"`
	LastAcknowledgementAt     pgtype.Timestamptz `json:"last_acknowledgement_at"`
	BlockedAt                 pgtype.Timestamptz `json:"blocked_at"`
	Version                   int64              `json:"version"`
	CreatedAt                 time.Time          `json:"created_at"`
	UpdatedAt                 time.Time          `json:"updated_at"`
}

type ConversationAiStateEvent struct {
	ID                  uuid.UUID       `json:"id"`
	AccountID           uuid.UUID       `json:"account_id"`
	ConversationID      uuid.UUID       `json:"conversation_id"`
	ActorUserID         *uuid.UUID      `json:"actor_user_id"`
	FromState           *string         `json:"from_state"`
	ToState             string          `json:"to_state"`
	Reason              *string         `json:"reason"`
	TriggeringMessageID *uuid.UUID      `json:"triggering_message_id"`
	Metadata            json.RawMessage `json:"metadata"`
	CreatedAt           time.Time       `json:"created_at"`
}

type ConversationRead struct {
	ID             uuid.UUID `json:"id"`
	AccountID      uuid.UUID `json:"account_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
	LastReadAt     time.Time `json:"last_read_at"`
}

type ConversationSummary struct {
	ID                       uuid.UUID       `json:"id"`
	AccountID                uuid.UUID       `json:"account_id"`
	ConversationID           uuid.UUID       `json:"conversation_id"`
	SummaryFields            json.RawMessage `json:"summary_fields"`
	GeneratedAt              time.Time       `json:"generated_at"`
	MessageCountAtGeneration int32           `json:"message_count_at_generation"`
}

type KbConcept struct {
	ID        uuid.UUID       `json:"id"`
	AccountID uuid.UUID       `json:"account_id"`
	Slug      string          `json:"slug"`
	Type      string          `json:"type"`
	Title     string          `json:"title"`
	Tags      []string        `json:"tags"`
	BodyText  string          `json:"body_text"`
	Embedding pgvector.Vector `json:"embedding"`
	Source    string          `json:"source"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type KbIngestion struct {
	ID          uuid.UUID          `json:"id"`
	AccountID   uuid.UUID          `json:"account_id"`
	RequestedBy *uuid.UUID         `json:"requested_by"`
	Status      string             `json:"status"`
	RawText     string             `json:"raw_text"`
	Error       *string            `json:"error"`
	CreatedAt   time.Time          `json:"created_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type KbIngestionItem struct {
	ID          uuid.UUID  `json:"id"`
	IngestionID uuid.UUID  `json:"ingestion_id"`
	Position    int32      `json:"position"`
	Type        string     `json:"type"`
	Title       string     `json:"title"`
	Tags        []string   `json:"tags"`
	BodyText    string     `json:"body_text"`
	Status      string     `json:"status"`
	ConceptID   *uuid.UUID `json:"concept_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type KbIngestionPattern struct {
	ID                uuid.UUID  `json:"id"`
	IngestionID       uuid.UUID  `json:"ingestion_id"`
	Position          int32      `json:"position"`
	CanonicalQuestion string     `json:"canonical_question"`
	AnswerText        string     `json:"answer_text"`
	TriggerPhrases    []string   `json:"trigger_phrases"`
	Status            string     `json:"status"`
	PatternID         *uuid.UUID `json:"pattern_id"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

type KbMiningRun struct {
	ID                 uuid.UUID `json:"id"`
	AccountID          uuid.UUID `json:"account_id"`
	RunAt              time.Time `json:"run_at"`
	WindowStart        time.Time `json:"window_start"`
	WindowEnd          time.Time `json:"window_end"`
	MessagesScanned    int32     `json:"messages_scanned"`
	ClustersFound      int32     `json:"clusters_found"`
	SuggestionsCreated int32     `json:"suggestions_created"`
}

type Lead struct {
	ID              uuid.UUID  `json:"id"`
	AccountID       uuid.UUID  `json:"account_id"`
	ConversationID  uuid.UUID  `json:"conversation_id"`
	PipelineID      uuid.UUID  `json:"pipeline_id"`
	CurrentStateKey string     `json:"current_state_key"`
	Tags            []string   `json:"tags"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type LeadNote struct {
	ID           uuid.UUID  `json:"id"`
	AccountID    uuid.UUID  `json:"account_id"`
	LeadID       uuid.UUID  `json:"lead_id"`
	AuthorUserID *uuid.UUID `json:"author_user_id"`
	Body         string     `json:"body"`
	CreatedAt    time.Time  `json:"created_at"`
}

type LeadPipeline struct {
	ID        uuid.UUID       `json:"id"`
	AccountID uuid.UUID       `json:"account_id"`
	Name      string          `json:"name"`
	States    json.RawMessage `json:"states"`
	CreatedAt time.Time       `json:"created_at"`
}

type LeadStateHistory struct {
	ID        uuid.UUID  `json:"id"`
	AccountID uuid.UUID  `json:"account_id"`
	LeadID    uuid.UUID  `json:"lead_id"`
	FromState *string    `json:"from_state"`
	ToState   string     `json:"to_state"`
	ChangedBy *uuid.UUID `json:"changed_by"`
	ChangedAt time.Time  `json:"changed_at"`
}

type MediaObject struct {
	ID          uuid.UUID  `json:"id"`
	AccountID   uuid.UUID  `json:"account_id"`
	MessageID   *uuid.UUID `json:"message_id"`
	ChannelID   uuid.UUID  `json:"channel_id"`
	ProviderRef *string    `json:"provider_ref"`
	Filename    *string    `json:"filename"`
	MimeType    string     `json:"mime_type"`
	SizeBytes   int64      `json:"size_bytes"`
	StorageKey  *string    `json:"storage_key"`
	ExpiresAt   time.Time  `json:"expires_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type Message struct {
	ID                uuid.UUID          `json:"id"`
	AccountID         uuid.UUID          `json:"account_id"`
	ConversationID    uuid.UUID          `json:"conversation_id"`
	Direction         string             `json:"direction"`
	SenderType        string             `json:"sender_type"`
	SenderUserID      *uuid.UUID         `json:"sender_user_id"`
	ContentType       string             `json:"content_type"`
	Content           json.RawMessage    `json:"content"`
	ExternalMessageID *string            `json:"external_message_id"`
	CreatedAt         time.Time          `json:"created_at"`
	IdempotencyKey    *string            `json:"idempotency_key"`
	ProviderMessageID *string            `json:"provider_message_id"`
	ReplyToMessageID  *uuid.UUID         `json:"reply_to_message_id"`
	DeliveryStatus    string             `json:"delivery_status"`
	DeliveryDetail    *string            `json:"delivery_detail"`
	ProviderTimestamp pgtype.Timestamptz `json:"provider_timestamp"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type MessageOutbox struct {
	ID           uuid.UUID          `json:"id"`
	AccountID    uuid.UUID          `json:"account_id"`
	ChannelID    uuid.UUID          `json:"channel_id"`
	MessageID    uuid.UUID          `json:"message_id"`
	Provider     string             `json:"provider"`
	Command      json.RawMessage    `json:"command"`
	Attempts     int32              `json:"attempts"`
	AvailableAt  time.Time          `json:"available_at"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	ClaimedBy    *string            `json:"claimed_by"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
	LastError    *string            `json:"last_error"`
	CreatedAt    time.Time          `json:"created_at"`
}

type MessageReaction struct {
	ID                uuid.UUID `json:"id"`
	AccountID         uuid.UUID `json:"account_id"`
	MessageID         uuid.UUID `json:"message_id"`
	SenderExternalID  string    `json:"sender_external_id"`
	Emoji             string    `json:"emoji"`
	ProviderTimestamp time.Time `json:"provider_timestamp"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Pattern struct {
	ID                uuid.UUID       `json:"id"`
	AccountID         uuid.UUID       `json:"account_id"`
	TriggerPhrases    []string        `json:"trigger_phrases"`
	CanonicalQuestion string          `json:"canonical_question"`
	AnswerText        string          `json:"answer_text"`
	Embedding         pgvector.Vector `json:"embedding"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type ProcessedAdapterEvent struct {
	Provider    string    `json:"provider"`
	EventID     string    `json:"event_id"`
	ChannelID   uuid.UUID `json:"channel_id"`
	ProcessedAt time.Time `json:"processed_at"`
}

type ProviderConnection struct {
	ChannelID       uuid.UUID `json:"channel_id"`
	AccountID       uuid.UUID `json:"account_id"`
	Provider        string    `json:"provider"`
	State           string    `json:"state"`
	Detail          *string   `json:"detail"`
	RemoteAccountID *string   `json:"remote_account_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	AccountID         uuid.UUID `json:"account_id"`
	Email             *string   `json:"email"`
	PasswordHash      string    `json:"password_hash"`
	Role              string    `json:"role"`
	CreatedAt         time.Time `json:"created_at"`
	ReplyModeOverride *string   `json:"reply_mode_override"`
	Username          *string   `json:"username"`
}
