// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pipelines.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const findLeadsInStateKeys = `-- name: FindLeadsInStateKeys :many
SELECT id
FROM leads
WHERE account_id = $1 AND current_state_key = ANY($2::text[])
`

type FindLeadsInStateKeysParams struct {
	AccountID uuid.UUID `json:"account_id"`
	StateKeys []string  `json:"state_keys"`
}

func (q *Queries) FindLeadsInStateKeys(ctx context.Context, arg FindLeadsInStateKeysParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, findLeadsInStateKeys, arg.AccountID, arg.StateKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPipelineStates = `-- name: GetPipelineStates :one
SELECT states
FROM lead_pipelines
WHERE id = $1 AND account_id = $2
`

type GetPipelineStatesParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) GetPipelineStates(ctx context.Context, arg GetPipelineStatesParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getPipelineStates, arg.ID, arg.AccountID)
	var states json.RawMessage
	err := row.Scan(&states)
	return states, err
}

const listPipelinesByAccount = `-- name: ListPipelinesByAccount :many
SELECT id, account_id, name, states, created_at
FROM lead_pipelines
WHERE account_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPipelinesByAccount(ctx context.Context, accountID uuid.UUID) ([]LeadPipeline, error) {
	rows, err := q.db.Query(ctx, listPipelinesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeadPipeline{}
	for rows.Next() {
		var i LeadPipeline
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.States,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipeline = `-- name: UpdatePipeline :exec
UPDATE lead_pipelines
SET name = $1, states = $2
WHERE id = $3 AND account_id = $4
`

type UpdatePipelineParams struct {
	Name      string          `json:"name"`
	States    json.RawMessage `json:"states"`
	ID        uuid.UUID       `json:"id"`
	AccountID uuid.UUID       `json:"account_id"`
}

func (q *Queries) UpdatePipeline(ctx context.Context, arg UpdatePipelineParams) error {
	_, err := q.db.Exec(ctx, updatePipeline,
		arg.Name,
		arg.States,
		arg.ID,
		arg.AccountID,
	)
	return err
}
