// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package dbgen

import (
	"context"
)

const deleteSessionsByAccountID = `-- name: DeleteSessionsByAccountID :exec
DELETE FROM sessions
WHERE session_data_json(data)->>'account_id' = $1::text
`

func (q *Queries) DeleteSessionsByAccountID(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByAccountID, accountID)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE session_data_json(data)->>'user_id' = $1::text
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}
