// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package dbgen

import (
	"context"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expiry < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionsByAccountID = `-- name: DeleteSessionsByAccountID :exec
DELETE FROM sessions
WHERE convert_from(data, 'UTF8')::jsonb->>'account_id' = $1::text
`

func (q *Queries) DeleteSessionsByAccountID(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByAccountID, accountID)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE convert_from(data, 'UTF8')::jsonb->>'user_id' = $1::text
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}
