// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: summaries.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getConversationSummary = `-- name: GetConversationSummary :one
SELECT s.summary_fields,
       s.generated_at,
       s.message_count_at_generation,
       (SELECT COUNT(*) FROM messages m
         WHERE m.conversation_id = s.conversation_id AND m.account_id = s.account_id)::int AS current_message_count
FROM conversation_summaries s
WHERE s.conversation_id = $1 AND s.account_id = $2
`

type GetConversationSummaryParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	AccountID      uuid.UUID `json:"account_id"`
}

type GetConversationSummaryRow struct {
	SummaryFields            json.RawMessage `json:"summary_fields"`
	GeneratedAt              time.Time       `json:"generated_at"`
	MessageCountAtGeneration int32           `json:"message_count_at_generation"`
	CurrentMessageCount      int32           `json:"current_message_count"`
}

// Account-scoped read of the one summary row per conversation, with the live
// message count so callers can tell whether newer messages exist.
func (q *Queries) GetConversationSummary(ctx context.Context, arg GetConversationSummaryParams) (GetConversationSummaryRow, error) {
	row := q.db.QueryRow(ctx, getConversationSummary, arg.ConversationID, arg.AccountID)
	var i GetConversationSummaryRow
	err := row.Scan(
		&i.SummaryFields,
		&i.GeneratedAt,
		&i.MessageCountAtGeneration,
		&i.CurrentMessageCount,
	)
	return i, err
}
