// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const checkUserExistsInAccount = `-- name: CheckUserExistsInAccount :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE id = $1 AND account_id = $2
)
`

type CheckUserExistsInAccountParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) CheckUserExistsInAccount(ctx context.Context, arg CheckUserExistsInAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExistsInAccount, arg.ID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUserInAccount = `-- name: CountUserInAccount :one
SELECT COUNT(*)
FROM users
WHERE id = $1 AND account_id = $2
`

type CountUserInAccountParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) CountUserInAccount(ctx context.Context, arg CountUserInAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserInAccount, arg.ID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT COUNT(*)
FROM users
WHERE email = $1::text
`

func (q *Queries) CountUsersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (account_id, email, username, password_hash, role)
VALUES ($1, NULLIF($2::text, ''), NULLIF($3::text, ''), $4, $5)
RETURNING id, account_id, COALESCE(email, '') AS email, COALESCE(username, '') AS username, role, created_at
`

type CreateUserParams struct {
	AccountID    uuid.UUID `json:"account_id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

type CreateUserRow struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.AccountID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createUserWithExplicitID = `-- name: CreateUserWithExplicitID :exec
INSERT INTO users (id, account_id, email, username, password_hash, role, created_at)
VALUES ($1, $2, NULLIF($3::text, ''), NULLIF($4::text, ''), $5, $6, $7)
`

type CreateUserWithExplicitIDParams struct {
	ID           uuid.UUID `json:"id"`
	AccountID    uuid.UUID `json:"account_id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateUserWithExplicitID(ctx context.Context, arg CreateUserWithExplicitIDParams) error {
	_, err := q.db.Exec(ctx, createUserWithExplicitID,
		arg.ID,
		arg.AccountID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const deleteUserFromAccount = `-- name: DeleteUserFromAccount :exec
DELETE FROM users
WHERE id = $1 AND account_id = $2
`

type DeleteUserFromAccountParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) DeleteUserFromAccount(ctx context.Context, arg DeleteUserFromAccountParams) error {
	_, err := q.db.Exec(ctx, deleteUserFromAccount, arg.ID, arg.AccountID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, account_id, COALESCE(email, '') AS email, COALESCE(username, '') AS username, password_hash, role, created_at
FROM users
WHERE email = $1::text
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	AccountID    uuid.UUID `json:"account_id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, account_id, COALESCE(email, '') AS email, COALESCE(username, '') AS username, role, created_at
FROM users
WHERE id = $1 AND account_id = $2
`

type GetUserByIDParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

type GetUserByIDRow struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.AccountID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserBySlugIdentifier = `-- name: GetUserBySlugIdentifier :one
SELECT u.id, u.account_id, COALESCE(u.email, '') AS email, COALESCE(u.username, '') AS username, u.password_hash, u.role, u.created_at
FROM users u
JOIN accounts a ON a.id = u.account_id
WHERE (a.slug || '-' || u.username) = $1::text
LIMIT 1
`

type GetUserBySlugIdentifierRow struct {
	ID           uuid.UUID `json:"id"`
	AccountID    uuid.UUID `json:"account_id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetUserBySlugIdentifier(ctx context.Context, identifier string) (GetUserBySlugIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getUserBySlugIdentifier, identifier)
	var i GetUserBySlugIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserReplyMode = `-- name: GetUserReplyMode :one
SELECT u.reply_mode_override, a.settings
FROM users u
JOIN accounts a ON a.id = u.account_id
WHERE u.id = $1 AND u.account_id = $2
`

type GetUserReplyModeParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

type GetUserReplyModeRow struct {
	ReplyModeOverride *string         `json:"reply_mode_override"`
	Settings          json.RawMessage `json:"settings"`
}

func (q *Queries) GetUserReplyMode(ctx context.Context, arg GetUserReplyModeParams) (GetUserReplyModeRow, error) {
	row := q.db.QueryRow(ctx, getUserReplyMode, arg.ID, arg.AccountID)
	var i GetUserReplyModeRow
	err := row.Scan(&i.ReplyModeOverride, &i.Settings)
	return i, err
}

const listUsersByAccount = `-- name: ListUsersByAccount :many
SELECT id, account_id, COALESCE(email, '') AS email, COALESCE(username, '') AS username, role, created_at
FROM users
WHERE account_id = $1
ORDER BY created_at ASC
`

type ListUsersByAccountRow struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListUsersByAccount(ctx context.Context, accountID uuid.UUID) ([]ListUsersByAccountRow, error) {
	rows, err := q.db.Query(ctx, listUsersByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByAccountRow{}
	for rows.Next() {
		var i ListUsersByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Email,
			&i.Username,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $2 AND account_id = $3
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
	AccountID    uuid.UUID `json:"account_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID, arg.AccountID)
	return err
}

const updateUserPasswordGlobal = `-- name: UpdateUserPasswordGlobal :exec
UPDATE users
SET password_hash = $1
WHERE id = $2
`

type UpdateUserPasswordGlobalParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPasswordGlobal(ctx context.Context, arg UpdateUserPasswordGlobalParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordGlobal, arg.PasswordHash, arg.ID)
	return err
}

const updateUserReplyMode = `-- name: UpdateUserReplyMode :exec
UPDATE users
SET reply_mode_override = $1
WHERE id = $2 AND account_id = $3
`

type UpdateUserReplyModeParams struct {
	ReplyModeOverride *string   `json:"reply_mode_override"`
	ID                uuid.UUID `json:"id"`
	AccountID         uuid.UUID `json:"account_id"`
}

func (q *Queries) UpdateUserReplyMode(ctx context.Context, arg UpdateUserReplyModeParams) error {
	_, err := q.db.Exec(ctx, updateUserReplyMode, arg.ReplyModeOverride, arg.ID, arg.AccountID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $1
WHERE id = $2 AND account_id = $3
`

type UpdateUserRoleParams struct {
	Role      string    `json:"role"`
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID, arg.AccountID)
	return err
}
